./kafka-topics.sh --create --topic topic0 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic1 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic2 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic3 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic4 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic5 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic6 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic7 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic8 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic9 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic10 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic11 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic12 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic13 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic14 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic15 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic16 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic17 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic18 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic19 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic20 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic21 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic22 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic23 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic24 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic25 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic26 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic27 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic28 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic29 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic30 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic31 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic32 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic33 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic34 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic35 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic36 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic37 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic38 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic39 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic40 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic41 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic42 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic43 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic44 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic45 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic46 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic47 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic48 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic49 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic50 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic51 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic52 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic53 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic54 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic55 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic56 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic57 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic58 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic59 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic60 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic61 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic62 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic63 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic64 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic65 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic66 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic67 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic68 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic69 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic70 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic71 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic72 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic73 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic74 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic75 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic76 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic77 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic78 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic79 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic80 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic81 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic82 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic83 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic84 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic85 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic86 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic87 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic88 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic89 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic90 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic91 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic92 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic93 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic94 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic95 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic96 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic97 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic98 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic99 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic100 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic101 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic102 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic103 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic104 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic105 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic106 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic107 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic108 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic109 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic110 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic111 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic112 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic113 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic114 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic115 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic116 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic117 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic118 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic119 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic120 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic121 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic122 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic123 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic124 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic125 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic126 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
./kafka-topics.sh --create --topic topic127 --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
